# Generated by Django 4.2.4 on 2023-08-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complilation',
            name='game',
            field=models.ManyToManyField(blank=True, null=True, to='games.game'),
        ),
    ]
