# Generated by Django 4.2.4 on 2024-01-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_complilation_game_alter_game_categories_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Complilation',
            new_name='Compilation',
        ),
    ]
